/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_winterop_jrectangularhyperbola_Java2Win */

#ifndef _Included_com_winterop_jrectangularhyperbola_Java2Win
#define _Included_com_winterop_jrectangularhyperbola_Java2Win
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_winterop_jrectangularhyperbola_Java2Win
 * Method:    CppMessageBox
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_winterop_jrectangularhyperbola_Java2Win_CppMessageBox
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
